/* 
 * ParameterizationStore
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ParameterizationStore.Client.Client.SwaggerDateConverter;

namespace ParameterizationStore.Client.Model
{
    /// <summary>
    /// FieldsDefinition
    /// </summary>
    [DataContract]
        public partial class FieldsDefinition :  IEquatable<FieldsDefinition>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldsDefinition" /> class.
        /// </summary>
        /// <param name="mandatoryFields">mandatoryFields.</param>
        /// <param name="optionalFields">optionalFields.</param>
        public FieldsDefinition(List<FieldMetaData> mandatoryFields = default(List<FieldMetaData>), List<FieldMetaData> optionalFields = default(List<FieldMetaData>))
        {
            this.MandatoryFields = mandatoryFields;
            this.OptionalFields = optionalFields;
        }
        
        /// <summary>
        /// Gets or Sets MandatoryFields
        /// </summary>
        [DataMember(Name="mandatoryFields", EmitDefaultValue=false)]
        public List<FieldMetaData> MandatoryFields { get; set; }

        /// <summary>
        /// Gets or Sets OptionalFields
        /// </summary>
        [DataMember(Name="optionalFields", EmitDefaultValue=false)]
        public List<FieldMetaData> OptionalFields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FieldsDefinition {\n");
            sb.Append("  MandatoryFields: ").Append(MandatoryFields).Append("\n");
            sb.Append("  OptionalFields: ").Append(OptionalFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FieldsDefinition);
        }

        /// <summary>
        /// Returns true if FieldsDefinition instances are equal
        /// </summary>
        /// <param name="input">Instance of FieldsDefinition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FieldsDefinition input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MandatoryFields == input.MandatoryFields ||
                    this.MandatoryFields != null &&
                    input.MandatoryFields != null &&
                    this.MandatoryFields.SequenceEqual(input.MandatoryFields)
                ) && 
                (
                    this.OptionalFields == input.OptionalFields ||
                    this.OptionalFields != null &&
                    input.OptionalFields != null &&
                    this.OptionalFields.SequenceEqual(input.OptionalFields)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MandatoryFields != null)
                    hashCode = hashCode * 59 + this.MandatoryFields.GetHashCode();
                if (this.OptionalFields != null)
                    hashCode = hashCode * 59 + this.OptionalFields.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
