/* 
 * ParameterizationStore
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ParameterizationStore.Client.Client.SwaggerDateConverter;

namespace ParameterizationStore.Client.Model
{
    /// <summary>
    /// TransitionDto
    /// </summary>
    [DataContract]
        public partial class TransitionDto :  IEquatable<TransitionDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransitionDto" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="targetStateId">targetStateId.</param>
        /// <param name="sourceStateId">sourceStateId.</param>
        /// <param name="trigger">trigger.</param>
        public TransitionDto(string id = default(string), string targetStateId = default(string), string sourceStateId = default(string), SmTriggerDto trigger = default(SmTriggerDto))
        {
            this.Id = id;
            this.TargetStateId = targetStateId;
            this.SourceStateId = sourceStateId;
            this.Trigger = trigger;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets TargetStateId
        /// </summary>
        [DataMember(Name="targetStateId", EmitDefaultValue=false)]
        public string TargetStateId { get; set; }

        /// <summary>
        /// Gets or Sets SourceStateId
        /// </summary>
        [DataMember(Name="sourceStateId", EmitDefaultValue=false)]
        public string SourceStateId { get; set; }

        /// <summary>
        /// Gets or Sets Trigger
        /// </summary>
        [DataMember(Name="trigger", EmitDefaultValue=false)]
        public SmTriggerDto Trigger { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransitionDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TargetStateId: ").Append(TargetStateId).Append("\n");
            sb.Append("  SourceStateId: ").Append(SourceStateId).Append("\n");
            sb.Append("  Trigger: ").Append(Trigger).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransitionDto);
        }

        /// <summary>
        /// Returns true if TransitionDto instances are equal
        /// </summary>
        /// <param name="input">Instance of TransitionDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransitionDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.TargetStateId == input.TargetStateId ||
                    (this.TargetStateId != null &&
                    this.TargetStateId.Equals(input.TargetStateId))
                ) && 
                (
                    this.SourceStateId == input.SourceStateId ||
                    (this.SourceStateId != null &&
                    this.SourceStateId.Equals(input.SourceStateId))
                ) && 
                (
                    this.Trigger == input.Trigger ||
                    (this.Trigger != null &&
                    this.Trigger.Equals(input.Trigger))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.TargetStateId != null)
                    hashCode = hashCode * 59 + this.TargetStateId.GetHashCode();
                if (this.SourceStateId != null)
                    hashCode = hashCode * 59 + this.SourceStateId.GetHashCode();
                if (this.Trigger != null)
                    hashCode = hashCode * 59 + this.Trigger.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
